RabbitMQ:
  Host: localhost
  Port: 5672
  Username: analysis
  Password: analysis
  VHost: analysis

MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password:

Logging:
  Consumer:
    LogPath: /var/log/application/
    Logger: [SymfonyConsoleHandler, StreamHandler]


Application:
  PHPLoc:
    Binary: /var/application/vendor/phploc/phploc/composer/bin/phploc
    FilePattern: "*.php,*.inc"
  CVSAnaly:
    Binary: /var/tools/MetricsGrimoire/CVSAnalY/cvsanaly2
  GithubLinguist:
    WorkingDir: /var/tools/github-linguist

# currently not in use. Refactor consumer to use this block
Projects:
  TYPO3:
    MySQL:
      Database: typo3
    RabbitMQ:
      Exchange: TYPO3
    DownloadPath: /var/data/TYPO3
